ALTER TABLE clients ADD COLUMN IF NOT EXISTS linkedin text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS twitter text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS instagram text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS facebook text;