-- Seed marketplace with video resources and Apple-style design resources

INSERT INTO marketplace_products (title, description, price, old_price, category, rating, reviews_count, purchases_count, cover_image_url, platform, is_featured, discount_enabled, is_free, tags, type)
VALUES
-- Alex Hormozi Videos
('7 Business Concepts You''ve Never Heard of (But Will Make You LOTS of Money) — Ep 675', 'Alex Hormozi breaks down 7 powerful business concepts including LTGP:CAC, ROIC, Payback Period, and TAM. A must-watch for anyone serious about scaling. Available on Podbean and YouTube.', 0.00, NULL, 'courses', 5.0, 128, 340, 'https://images.unsplash.com/photo-1556761175-5972dc595fcd?auto=format&fit=crop&q=80&w=800', 'YouTube/Podcast', true, false, true, ARRAY['Hormozi','Business Concepts','LTGP','CAC','ROIC','TAM','Scaling'], 'video'),
('The 6 Levels of Making Money — Ep 955', 'Alex Hormozi explains the 6 levels of making money, covering deal structures, risk vs. reward, and income levels. Listen on Apple Podcasts and Castbox.', 0.00, NULL, 'courses', 4.9, 85, 210, 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&q=80&w=800', 'Podcast', false, false, true, ARRAY['Hormozi','Money','Deal Structures','Risk','Income Levels'], 'video'),
('Alex Hormozi''s Advice Will Leave You SPEECHLESS 3.0', 'A motivational edit featuring Hormozi''s most powerful advice on work ethic, mindset, and motivation. Direct YouTube Music link included.', 0.00, NULL, 'courses', 5.0, 210, 520, 'https://images.unsplash.com/photo-1506126613408-eca97ce0c8a8?auto=format&fit=crop&q=80&w=800', 'YouTube Music', true, false, true, ARRAY['Hormozi','Motivation','Work Ethic','Mindset'], 'video'),
('Alex Hormozi: 6 Secretos para Hacer Ofertas IRRESISTIBLES', 'Spanish-language breakdown of Hormozi''s $100M Offers framework. Covers irresistible offers, value equation, and pricing strategy. Direct YouTube Music link included.', 0.00, NULL, 'courses', 4.8, 95, 180, 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?auto=format&fit=crop&q=80&w=800', 'YouTube Music', false, false, true, ARRAY['Hormozi','Offers','Spanish','Pricing','Value Equation'], 'video'),

-- Gary Vaynerchuk Videos
('#AskGaryVee 244: Calling From The Arctic Circle', 'Classic GaryVee Q&A episode covering Facebook Groups, family business, and career advice. A direct YouTube Music podcast link serves as the source.', 0.00, NULL, 'courses', 4.9, 156, 380, 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=800', 'YouTube Music', false, false, true, ARRAY['GaryVee','Social Media','Business','Q&A'], 'video'),
('Tea with GaryVee ep.81: Growing Your Business, Social Media Strategy, AI & What''s Next', 'Gary Vaynerchuk covers brand building, consistency, risk-taking, and why this is the "new golden years" for taking risks. Direct YouTube Music podcast link included.', 0.00, NULL, 'courses', 5.0, 198, 450, 'https://images.unsplash.com/photo-1611162616305-c69b3fa7d0c2?auto=format&fit=crop&q=80&w=800', 'YouTube Music', true, false, true, ARRAY['GaryVee','Brand Building','AI','Social Media Strategy'], 'video'),

-- Apple Design Resources
('Apple Design Resources — Official UI Kit', 'Apple''s official UI kits for iOS, iPadOS, and visionOS. The most accurate and up-to-date components, colors, and fonts for designing native Apple apps. Available directly in Figma''s asset panel or via Apple''s developer site.', 0.00, NULL, 'templates', 5.0, 320, 890, 'https://images.unsplash.com/photo-1620712943544-bb1a2cb6c3e5?auto=format&fit=crop&q=80&w=800', 'Figma, Sketch', true, false, true, ARRAY['Apple','iOS','UI Kit','Design System','Official'], 'resource'),
('visionOS 26 UI Kit', 'Official Apple design kit for visionOS. Contains UI components, views, system interfaces, and materials for spatial computing app designs. Figma Community link included.', 0.00, NULL, 'templates', 4.9, 145, 320, 'https://images.unsplash.com/photo-1593508518720-66b6d84a1c100?auto=format&fit=crop&q=80&w=800', 'Figma', false, false, true, ARRAY['Apple','visionOS','Spatial Computing','UI Kit'], 'resource'),
('Apple SF & NY Fonts (Windows)', 'The official Apple system fonts (San Francisco and New York) ported for use on Windows and other non-Apple platforms. Available in OTF and TTF formats via GitHub.', 0.00, NULL, 'templates', 4.8, 210, 560, 'https://images.unsplash.com/photo-1611606062305-140d0e1e7b63?auto=format&fit=crop&q=80&w=800', 'Windows, GitHub', false, false, true, ARRAY['Apple','Fonts','SF Pro','New York','Typography'], 'resource'),
('iOS 27 with Liquid Glass UI Kit', 'A free, non-official Figma UI kit featuring the new "Liquid Glass" visual direction for iOS and iPadOS 27. Perfect for drafting modern, Apple-style mobile and tablet interfaces.', 0.00, NULL, 'templates', 4.7, 89, 240, 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=800', 'Figma', true, false, true, ARRAY['iOS 27','Liquid Glass','UI Kit','Figma','Apple'], 'resource'),
('The Survival Kit for iOS 18', 'A comprehensive design kit that includes iOS 18 components, variables for light/dark/accessibility modes, SF Symbols, and two interactive prototypes of real apps (Book Truck and NEU Ski).', 0.00, NULL, 'templates', 4.9, 176, 410, 'https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&q=80&w=800', 'Figma', false, false, true, ARRAY['iOS 18','UI Kit','SF Symbols','Prototypes','Design System'], 'resource'),
('iOS 26 Interface Builder', 'A free, architecture-heavy UI kit inheriting from Apple''s official library. Features tokens, auto-layouts, variables, and production-ready templates for efficient, scalable iOS workflows.', 0.00, NULL, 'templates', 4.8, 134, 298, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800', 'Figma', false, false, true, ARRAY['iOS 26','Interface Builder','Tokens','Auto-layout','Apple'], 'resource'),
('Apple iOS 17 UI Kit (Upgraded)', 'An enhanced version of the iOS 17 UI Kit with a comprehensive set of components, widgets, and system views for creating highly realistic iOS app designs.', 0.00, NULL, 'templates', 4.7, 112, 265, 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=800', 'Figma', false, false, true, ARRAY['iOS 17','UI Kit','Components','Widgets','Apple'], 'resource'),
('Design System Hub — Figma Plugin', 'A Figma plugin that provides a curated library of over 150 design systems from top companies (Apple, Google, Microsoft). Instant access to official links and resources for benchmarking and inspiration.', 0.00, NULL, 'toolkits', 4.6, 78, 190, 'https://images.unsplash.com/photo-1561070791-2526d30994b8?auto=format&fit=crop&q=80&w=800', 'Figma Plugin', false, false, true, ARRAY['Design Systems','Figma Plugin','Apple','Google','Microsoft'], 'resource'),

-- Icon Sets
('Buno 32px 4400+ Icons', 'A massive library of over 4,400 clean, linear duocolor icons. Built on a 32px grid with 2px strokes, making them ideal for interfaces, diagrams, and presentations. Free for commercial use with credit.', 0.00, NULL, 'graphics', 4.8, 245, 670, 'https://images.unsplash.com/photo-1611162616475-46b635ca686a?auto=format&fit=crop&q=80&w=800', 'Figma, SVG', true, false, true, ARRAY['Icons','4400+','Duocolor','32px','Commercial Use'], 'resource'),

-- Developer & Productivity Tools
('Apple Bento Grid Generator', 'A presentation card generator that produces self-contained HTML for Apple-style bento grid layouts. Perfect for quickly creating polished, pixel-aware dashboard and presentation-style visuals without a design app.', 0.00, NULL, 'toolkits', 4.7, 98, 215, 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&q=80&w=800', 'Windows, Web', false, false, true, ARRAY['Bento Grid','HTML Generator','Apple Style','Dashboard'], 'resource'),
('Apple Keynote Presentation Template', 'An Apple-inspired presentation template with a sleek black "Bento" design and Apple-style UI elements. Includes 18 customizable slides, perfect for product launches, keynotes, or team meetings.', 0.00, NULL, 'docs', 4.8, 167, 385, 'https://images.unsplash.com/photo-1531403009284-440e0cc91998?auto=format&fit=crop&q=80&w=800', 'PowerPoint, Google Slides', true, false, true, ARRAY['Keynote','Presentation','Bento','Apple','Template'], 'resource'),

-- Premium Design Systems
('Universal Design System', 'Sleek, scalable, Apple-inspired system with color tokens, typography, 1500 icons, mouse cursors, desktop & mobile components, and dark mode support. Free for personal and commercial use.', 0.00, NULL, 'templates', 4.9, 189, 430, 'https://images.unsplash.com/photo-1558655146-d093a8b7b6ce?auto=format&fit=crop&q=80&w=800', 'Figma', true, false, true, ARRAY['Design System','Apple','Dark Mode','1500 Icons','Tokens'], 'resource'),
('Apple UI — Free UI Kit', 'Recreated Apple website UI kit with adaptable, pixel-perfect templates and components for crafting Apple-style web interfaces.', 0.00, NULL, 'templates', 4.6, 134, 310, 'https://images.unsplash.com/photo-1493421410774-3fc5c1d6e6e0?auto=format&fit=crop&q=80&w=800', 'Figma', false, false, true, ARRAY['Apple','Web UI','Pixel Perfect','Templates'], 'resource'),

-- Website & Landing Page Templates
('Apple-Inspired Landing Page', 'Minimalistic Bubble template mirroring Apple''s iconic homepage aesthetic. Free, works best on paid Bubble plan.', 0.00, NULL, 'templates', 4.5, 67, 145, 'https://images.unsplash.com/photo-1467232004584-a377d16e30d8?auto=format&fit=crop&q=80&w=800', 'Bubble', false, false, true, ARRAY['Landing Page','Apple','Bubble','Minimalist'], 'resource'),
('Apple Inspired Portfolio (Astro)', 'Highly minimalist portfolio built with Astro, TailwindCSS, GSAP animations, Three.js, and React components. Fully responsive.', 0.00, NULL, 'templates', 4.8, 112, 260, 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?auto=format&fit=crop&q=80&w=800', 'Astro', false, false, true, ARRAY['Portfolio','Astro','TailwindCSS','GSAP','Three.js'], 'resource'),
('Austin & Velina Framer Templates', 'Clean, modern Framer templates. Austin is popular for Apple-inspired portfolios; Velina is free and built for interior design businesses.', 0.00, NULL, 'templates', 4.7, 89, 198, 'https://images.unsplash.com/photo-1545239351-1141bd82f5d1?auto=format&fit=crop&q=80&w=800', 'Framer', false, false, true, ARRAY['Framer','Portfolio','Apple','Interior Design'], 'resource'),

-- Developer & AI Tools
('Apple Design Skill — AI Skill', 'Open-source AI Skill guiding coding assistants to generate Apple-style frontend UI code. Includes design tokens, typography engine, copywriting optimizer, and layout patterns. Compatible with OpenClaw and Claude Code.', 0.00, NULL, 'toolkits', 4.9, 156, 375, 'https://images.unsplash.com/photo-1677442136019-21780ecad99e?auto=format&fit=crop&q=80&w=800', 'GitHub', true, false, true, ARRAY['AI Skill','Apple','Design Tokens','Claude Code','OpenClaw'], 'resource'),

-- Mockups & Presentation Assets
('Apple Product Mockups (PSD)', 'Free PSD mockups for iMac, iPad, iPhone, MacBook, Apple Watch. Editable smart objects for creating beautiful product presentations and marketing materials.', 0.00, NULL, 'graphics', 4.8, 234, 580, 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&q=80&w=800', 'PSD', true, false, true, ARRAY['Mockups','PSD','iMac','iPhone','MacBook','Apple Watch'], 'resource'),

-- Typography Tools
('iPhone Font Generator', 'Free iOS-style typography tool with live preview. Customize fonts, spacing, shadows, and backgrounds. Export PNG, SVG, or PDF. Apply clean, light, midnight, frost, or gradient presets.', 0.00, NULL, 'toolkits', 4.6, 145, 320, 'https://images.unsplash.com/photo-1456086283740-9bf9777f1c100?auto=format&fit=crop&q=80&w=800', 'Web', false, false, true, ARRAY['Typography','Font Generator','iOS','PNG','SVG'], 'resource');
